# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' A svd algorithm with the option for missing values.
#'
#' This function implemented a MM algorithm to fit a svd on a quantitaive data
#' set with missing values. The details of this function can be found
#' in \url{https://arxiv.org/abs/1902.06241}.
#'
#' @param X a quantitative data set
#' @param R the number of PCs
#' @param opts a list contains the setting for the algorithm. \itemize{
#' \item tol_obj: tolerance for relative change of hist_obj, default:1E-6;
#' \item maxit: max number of iterations, default: 1000;
#' }
#'
#' @return This function returns a list contains \itemize{
#' \item U: the left singular vectors
#' \item S: a column vector contains the singular values
#' \item V: the right singular vectors
#' \item iter: the number of iterations used
#' \item diagnose: records hist_obj and rel_obj
#' }
#'
#' @import RSpectra
#' 
#' @examples
#' \dontrun{svd_mis(X,R=3,opts=list())}
#'
#' @export
svd_mis <- function(X, R, opts) {
    .Call('_RpESCA2_svd_mis', PACKAGE = 'RpESCA2', X, R, opts)
}

#' Model selection of a svd model using missing value based CV error.
#' 
#' This function implemented a missing value based CV model selection approach.
#' First, ratio_mis percent elements are randomly selected as missing values. After
#' that a EM-SVD model is constructed to estimate the prediction error.
#' The details of this function can be found in \url{https://arxiv.org/abs/1902.06241}.
#'
#' @inheritParams alpha_estimation
#' @param ratio_mis the propotion of missing values
#'
#' @return This function returns a matrix contains the K-fold 
#' cross validation errors and the number of PCs used for 
#' model selection.
#'
#' @examples
#' \dontrun{svd_CV(X,K=3,Rs=1:15,ratio_mis=0.1,opts=list())}
#'
#' @export
svd_CV <- function(X, K, Rs, ratio_mis, opts) {
    .Call('_RpESCA2_svd_CV', PACKAGE = 'RpESCA2', X, K, Rs, ratio_mis, opts)
}

scad_sg <- function(x, gamma, lambda) {
    .Call('_RpESCA2_scad_sg', PACKAGE = 'RpESCA2', x, gamma, lambda)
}

